version: "3.9"

services:
  app:
    container_name: app
    restart: always
    volumes:
      - ./app:/home/node/app/app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
